// deployment/docker/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tmf632-service'
    static_configs:
      - targets: ['tmf632-service:8080']
    metrics_path: '/metrics'
    scheme: 'http'
